# GICS sector lookup for the STOXX 600 universe 
# (all the unique tickers being part of the index at least once during 2006-2026)
#
# Import with:
#     from src.sector_mapping import SECTOR_MAP, get_sector
#
# The full 11-sector GICS classification is used.
# Tickers use Bloomberg format: "TICKER EXCHANGE" (e.g. "ASML NA").

SECTOR_MAP: dict[str, str] = {

    "TTE FP":    "Energy",
    "ENI IM":    "Energy",
    "REP SQ":    "Energy",
    "EQNR NO":   "Energy",
    "RWE GY":    "Energy",
    "NESTE FH":  "Energy",
    "FGP LN":    "Energy",
    "TLW LN":    "Energy",
    "CNE LN":    "Energy",
    "NHY NO":    "Energy",
    "PGS NO":    "Energy",
    "AKRBP NO":  "Energy",
    "FRO NO":    "Energy",
    "SB1NO NO":  "Energy",
    "ORRON SS":  "Energy",
    "RECSI NO":  "Energy",
    "ENTRA NO":  "Energy",
    "NEL NO":    "Energy",
    "SCATC NO":  "Energy",
    "BP/ LN":    "Energy",
    "SHELL NA":  "Energy",
    "OMV AV":    "Energy",
    "GALP PL":   "Energy",
    "VAR NO":    "Energy",
    "HTG LN":    "Energy",
    "PKN PW":    "Energy",
    "RUI FP":    "Energy",
    "AFR LN":    "Energy",
    "AMFW LN":   "Energy",
    "BB/ LN":    "Energy",
    "BG/ LN":    "Energy",
    "DGO ID":    "Energy",
    "FP/ LN":    "Energy",
    "FTI FP":    "Energy",
    "GENL LN":   "Energy",
    "OPHR LN":   "Energy",
    "PFC LN":    "Energy",
    "PGN PW":    "Energy",
    "RDSA NA":   "Energy",
    "SPI IM":    "Energy",
    "STO NA":    "Energy",
    "TCHNR FP":  "Energy",
    "ALWN GA":   "Energy",
    "BWO AV":    "Energy",
    "IEA AV":    "Energy",
    "PO/ LN":    "Energy",
    "SDIA SS":   "Energy",
    "TELL GA":   "Energy",
    # LOW CONFIDENCE ON THE FOLLOWING TICKERS
    "ALWN GA":   "Energy",
    "BWO AV":    "Energy",
    "IEA AV":    "Energy",
    "SDIA SS":   "Energy",
    "TELL GA":   "Energy",

    "AAL LN":    "Materials",
    "BAS GY":    "Materials",
    "AI FP":     "Materials",
    "AKZA NA":   "Materials",
    "ACX SQ":    "Materials",
    "LXS GY":    "Materials",
    "SDF GY":    "Materials",
    "SGL GY":    "Materials",
    "WCH GY":    "Materials",
    "EVK GY":    "Materials",
    "LIN GY":    "Materials",
    "NEM GY":    "Materials",
    "SOLB BB":   "Materials",
    "BOL SS":    "Materials",
    "KEMIRA FH": "Materials",
    "UPM FH":    "Materials",
    "ENRO SS":   "Materials",
    "SSABA SS":  "Materials",
    "SSABB SS":  "Materials",
    "RIO LN":    "Materials",
    "ANTO LN":   "Materials",
    "GLEN LN":   "Materials",
    "MRO LN":    "Materials",
    "CRH LN":    "Materials",
    "CRH ID":    "Materials",
    "JMAT LN":   "Materials",
    "SKG ID":    "Materials",
    "MNDI LN":   "Materials",
    "SIKA SE":   "Materials",
    "GIVN SE":   "Materials",
    "GF SE":     "Materials",
    "COTN SE":   "Materials",
    "MT NA":     "Materials",
    "PHR PL":    "Materials",
    "UMI BB":    "Materials",
    "YAR NO":    "Materials",
    "SCAB SS":   "Materials",
    "SKFB SS":   "Materials",
    "SAND SS":   "Materials",
    "HOLMB SS":  "Materials",
    "CRBN NA":   "Materials",
    "BZU IM":    "Materials",
    "CLN SE":    "Materials",
    "CRDA LN":   "Materials",
    "DSFIR NA":  "Materials",
    "HOLN SE":   "Materials",
    "KGH PW":    "Materials",
    "OCI NA":    "Materials",
    "SGO FP":    "Materials",
    "VCT LN":    "Materials",
    "VED LN":    "Materials",
    "ENRC LN":   "Materials",
    "1COV GY":   "Materials",
    "AMRZ SE":   "Materials",
    "BOC LN":    "Materials",
    "CEY LN":    "Materials",
    "CHR DC":    "Materials",
    "CLN SW":    "Materials",
    "DSM NA":    "Materials",
    "GIVN SW":   "Materials",
    "HOLN SW":   "Materials",
    "ICI LN":    "Materials",
    "KAZ LN":    "Materials",
    "LG FP":     "Materials",
    "LMI LN":    "Materials",
    "NSG NO":    "Materials",
    "POG LN":    "Materials",
    "POLY LN":   "Materials",
    "RPC LN":    "Materials",
    "RRS LN":    "Materials",
    "SIKA SW":   "Materials",
    "SMDS LN":   "Materials",
    "TITK GA":   "Materials",
    "XTA LN":    "Materials",
    "CAMX SS":   "Materials",
    "ALSYDB DC": "Materials",
    "BRSN LN":   "Materials",
    "CRG IM":    "Materials",
    "ERU ID":    "Materials",
    "GCC ID":    "Materials",
    "HGM NA":    "Materials",
    "LEO GY":    "Materials",
    "RHA FP":    "Materials",
    "RHANR FP":  "Materials",
    "SCVB SS":   "Materials",
    # LOW CONFIDENCE ON THE FOLLOWING TICKERS
    "CAMX SS":   "Materials",
    "ALSYDB DC": "Materials",
    "BRSN LN":   "Materials",
    "ERU ID":    "Materials",
    "GCC ID":    "Materials",
    "HGM NA":    "Materials",
    "SCVB SS":   "Materials",

    "1CNHI IM":  "Industrials",
    "AALB NA":   "Industrials",
    "ABBN SE":   "Industrials",
    "AIR FP":    "Industrials",
    "ACS SQ":    "Industrials",
    "ADEN SE":   "Industrials",
    "ADP FP":    "Industrials",
    "AENA SQ":   "Industrials",
    "ALO FP":    "Industrials",
    "AF FP":     "Industrials",
    "SIE GY":    "Industrials",
    "HO FP":     "Industrials",
    "DHL GY":    "Industrials",
    "RHM GY":    "Industrials",
    "TKA GY":    "Industrials",
    "ASSAB SS":  "Industrials",
    "ATCOA SS":  "Industrials",
    "GETIB SS":  "Industrials",
    "HEXAB SS":  "Industrials",
    "HUSQB SS":  "Industrials",
    "HPOLB SS":  "Industrials",
    "INDUA SS":  "Industrials",
    "LOOMIS SS": "Industrials",
    "SWECB SS":  "Industrials",
    "TRELB SS":  "Industrials",
    "VOLVB SS":  "Industrials",
    "ENG SQ":    "Industrials",
    "FER SQ":    "Industrials",
    "FCC SQ":    "Industrials",
    "GBF GY":    "Industrials",
    "HEI GY":    "Industrials",
    "HOT GY":    "Industrials",
    "PSM GY":    "Industrials",
    "TUI1 GY":   "Industrials",
    "GYC GY":    "Industrials",
    "HFG GY":    "Industrials",
    "ARO GY":    "Industrials",
    "KCO GY":    "Industrials",
    "UTDI GY":   "Industrials",
    "ENR GY":    "Industrials",
    "DEQ GY":    "Industrials",
    "FPE3 GY":   "Industrials",
    "FNTN GY":   "Industrials",
    "HDD GY":    "Industrials",
    "DB1 GY":    "Industrials",
    "LHA GY":    "Industrials",
    "BA/ LN":    "Industrials",
    "IMI LN":    "Industrials",
    "RR/ LN":    "Industrials",
    "RTO LN":    "Industrials",
    "SMIN LN":   "Industrials",
    "WEIR LN":   "Industrials",
    "RS1 LN":    "Industrials",
    "EXPN LN":   "Industrials",
    "ITRK LN":   "Industrials",
    "SXS LN":    "Industrials",
    "BNZL LN":   "Industrials",
    "PAGE LN":   "Industrials",
    "TCAP LN":   "Industrials",
    "LOG LN":    "Industrials",
    "ICG LN":    "Industrials",
    "HAS LN":    "Industrials",
    "BBY LN":    "Industrials",
    "MAB LN":    "Industrials",
    "MCG LN":    "Industrials",
    "ADM LN":    "Industrials",
    "SRP LN":    "Industrials",
    "BAB LN":    "Industrials",
    "DLN LN":    "Industrials",
    "WG/ LN":    "Industrials",
    "SHI LN":    "Industrials",
    "VSVS LN":   "Industrials",
    "DPLM LN":   "Industrials",
    "DRX LN":    "Industrials",
    "IAG LN":    "Industrials",
    "EZJ LN":    "Industrials",
    "CCL LN":    "Industrials",
    "DSV DC":    "Industrials",
    "ISS DC":    "Industrials",
    "FLS DC":    "Industrials",
    "NKT DC":    "Industrials",
    "ROCKB DC":  "Industrials",
    "MAERSKB DC":"Industrials",
    "SUBC NO":   "Industrials",
    "MOWI NO":   "Industrials",
    "ORK NO":    "Industrials",
    "BTRW LN":   "Industrials",
    "BWY LN":    "Industrials",
    "PSN LN":    "Industrials",
    "HWDN LN":   "Industrials",
    "GFTU LN":   "Industrials",
    "SPX LN":    "Industrials",
    "MTO LN":    "Industrials",
    "AHT LN":    "Industrials",
    "BOK LN":    "Industrials",
    "ESNT LN":   "Industrials",
    "AXFO SS":   "Industrials",
    "LAGRB SS":  "Industrials",
    "EQT SS":    "Industrials",
    "INTRUM SS": "Industrials",
    "HTRO SS":   "Industrials",
    "AAK SS":    "Industrials",
    "ALFA SS":   "Industrials",
    "VALMT FH":  "Industrials",
    "METSO FH":  "Industrials",
    "KCR FH":    "Industrials",
    "MANTA FH":  "Industrials",
    "YIT FH":    "Industrials",
    "OUT1V FH":  "Industrials",
    "STERV FH":  "Industrials",
    "SPIE FP":   "Industrials",
    "EN FP":     "Industrials",
    "FR FP":     "Industrials",
    "FGR FP":    "Industrials",
    "GTT FP":    "Industrials",
    "FRVIA FP":  "Industrials",
    "NEX FP":    "Industrials",
    "COV FP":    "Industrials",
    "ERA FP":    "Industrials",
    "LR FP":     "Industrials",
    "ETL FP":    "Industrials",
    "SCR FP":    "Industrials",
    "TFI FP":    "Industrials",
    "MAU FP":    "Industrials",
    "RF FP":     "Industrials",
    "NK FP":     "Industrials",
    "DEC FP":    "Industrials",
    "GFC FP":    "Industrials",
    "MMT FP":    "Industrials",
    "VANTI FP":  "Industrials",
    "IPN FP":    "Industrials",
    "FDJU FP":   "Industrials",
    "ALE PW":    "Industrials",
    "DNP PW":    "Industrials",
    "BEZ LN":    "Industrials",
    "BPOST BB":  "Industrials",
    "SWON SE":   "Industrials",
    "OERL SE":   "Industrials",
    "BARN SE":   "Industrials",
    "DOKA SE":   "Industrials",
    "SIGN SE":   "Industrials",
    "ACLN SE":   "Industrials",
    "BKW SE":    "Industrials",
    "SRT3 GY":   "Industrials",
    "1U1 GY":    "Industrials",
    "STLAM IM":  "Industrials",
    "LDO IM":    "Industrials",
    "TEN IM":    "Industrials",
    "TRN IM":    "Industrials",
    "SPM IM":    "Industrials",
    "SRG IM":    "Industrials",
    "IP IM":     "Industrials",
    "FBK IM":    "Industrials",
    "IG IM":     "Industrials",
    "G1A GY":    "Industrials",
    "TMV GY":    "Industrials",
    "TGM GY":    "Industrials",
    "DTG GY":    "Industrials",
    "AT1 GY":    "Industrials",
    "UN0 GY":    "Industrials",
    "AUTO NO":   "Industrials",
    "BNR GY":    "Industrials",
    "CLLN LN":   "Industrials",
    "CPI LN":    "Industrials",
    "DCC LN":    "Industrials",
    "DUE GY":    "Industrials",
    "EPIA SS":   "Industrials",
    "FRA GY":    "Industrials",
    "GEBN SE":   "Industrials",
    "KNIN SE":   "Industrials",
    "KOG NO":    "Industrials",
    "RIEN SE":   "Industrials",
    "RXL FP":    "Industrials",
    "RYA ID":    "Industrials",
    "SAABB SS":  "Industrials",
    "SAF FP":    "Industrials",
    "SCYR SQ":   "Industrials",
    "SECUB SS":  "Industrials",
    "SKAB SS":   "Industrials",
    "SU FP":     "Industrials",
    "TE FP":     "Industrials",
    "WIZZ LN":   "Industrials",
    "WRT1V FH":  "Industrials",
    "AA/ LN":    "Industrials",
    "AB/ LN":    "Industrials",
    "ABBN SW":   "Industrials",
    "ABG/P SQ":  "Industrials",
    "ABP LN":    "Industrials",
    "ADEN SW":   "Industrials",
    "AFRY SS":   "Industrials",
    "AGK LN":    "Industrials",
    "AGL IM":    "Industrials",
    "ALFEN NA":  "Industrials",
    "AREVA FP":  "Industrials",
    "ASF FP":    "Industrials",
    "ATK LN":    "Industrials",
    "ATL IM":    "Industrials",
    "BAA LN":    "Industrials",
    "BOKA NA":   "Industrials",
    "CFAO FP":   "Industrials",
    "CHTR LN":   "Industrials",
    "DLAR LN":   "Industrials",
    "ELIOR FP":  "Industrials",
    "ESSR LN":   "Industrials",
    "GEBN SW":   "Industrials",
    "GKN LN":    "Industrials",
    "IDS LN":    "Industrials",
    "ISYS LN":   "Industrials",
    "IWG LN":    "Industrials",
    "KNIN SW":   "Industrials",
    "MAN GY":    "Industrials",
    "MGGT LN":   "Industrials",
    "MTRS SS":   "Industrials",
    "NCCB SS":   "Industrials",
    "NELES FH":  "Industrials",
    "OERL SW":   "Industrials",
    "PILK LN":   "Industrials",
    "PWTN SW":   "Industrials",
    "SGC LN":    "Industrials",
    "SIG LN":    "Industrials",
    "SRAIL SE":  "Industrials",
    "TNTE NA":   "Industrials",
    "VAR1 GY":   "Industrials",
    "VTG LN":    "Industrials",
    "ARR FP":    "Industrials",
    "AZA SS":    "Industrials",
    "CIBN VX":   "Industrials",
    "CPI AV":    "Industrials",
    "DCO DC":    "Industrials",
    "DOM SS":    "Industrials",
    "GE1 GY":    "Industrials",
    "HBAN SE":   "Industrials",
    "HIAB FH":   "Industrials",
    "HUBN SE":   "Industrials",
    "IFCN SE":   "Industrials",
    "KN FP":     "Industrials",
    "NXT FP":    "Industrials",
    "RENT NA":   "Industrials",
    "SGRE SQ":   "Industrials",
    "SGSN SW":   "Industrials",
    "TA NA":     "Industrials",
    "TOP DC":    "Industrials",
    "UNAT NA":   "Industrials",
    "VDOR NA":   "Industrials",
    "VNUA NA":   "Industrials",
    "ZEL SQ":    "Industrials",
    "AL IM":     "Industrials",
    "AL/ LN":    "Industrials",
    "ALT GY":    "Industrials",
    "AMEAS FH":  "Industrials",
    "AMV0 GY":   "Industrials",
    "ANGL ID":   "Industrials",
    "AU/ LN":    "Industrials",
    "AYV FP":    "Industrials",
    "BEFB BB":   "Industrials",
    "BIL IM":    "Industrials",
    "BL IM":     "Industrials",
    "BOB FP":    "Industrials",
    "BPT LN":    "Industrials",
    "BRE LN":    "Industrials",
    "CASS IM":   "Industrials",
    "COB LN":    "Industrials",
    "CSTL LN":   "Industrials",
    "DLG IM":    "Industrials",
    "FAD SQ":    "Industrials",
    "FDR SQ":    "Industrials",
    "FWB IM":    "Industrials",
    "GN5 ID":    "Industrials",
    "GTK IM":    "Industrials",
    "HAG GY":    "Industrials",
    "HSV LN":    "Industrials",
    "IAP LN":    "Industrials",
    "IBLA SQ":   "Industrials",
    "ICLL AV":   "Industrials",
    "IEC LN":    "Industrials",
    "IFL IM":    "Industrials",
    "IGY GY":    "Industrials",
    "IM NA":     "Industrials",
    "IOL IM":    "Industrials",
    "IT IM":     "Industrials",
    "JE/ LN":    "Industrials",
    "JPR LN":    "Industrials",
    "LTMC IM":   "Industrials",
    "MTP FP":    "Industrials",
    "NAT BB":    "Industrials",
    "NFDS LN":   "Industrials",
    "NUO NA":    "Industrials",
    "ORNBS FH":  "Industrials",
    "PC IM":     "Industrials",
    "POH1S FH":  "Industrials",
    "R IM":      "Industrials",
    "RCEA NA":   "Industrials",
    "REX LN":    "Industrials",
    "RUKN VX":   "Industrials",
    "SCH GY":    "Industrials",
    "SCTN LN":   "Industrials",
    "SRCG SE":   "Industrials",
    "VRD LN":    "Industrials",

    "MC FP":     "Consumer Discretionary",
    "CDI FP":    "Consumer Discretionary",
    "KER FP":    "Consumer Discretionary",
    "RMS FP":    "Consumer Discretionary",
    "RI FP":     "Consumer Discretionary",
    "PUB FP":    "Consumer Discretionary",
    "AC FP":     "Consumer Discretionary",
    "RNO FP":    "Consumer Discretionary",
    "ADS GY":    "Consumer Discretionary",
    "BMW GY":    "Consumer Discretionary",
    "MBG GY":    "Consumer Discretionary",
    "VOW GY":    "Consumer Discretionary",
    "VOW3 GY":   "Consumer Discretionary",
    "PAH3 GY":   "Consumer Discretionary",
    "PUM GY":    "Consumer Discretionary",
    "HNR1 GY":   "Consumer Discretionary",
    "BOSS GY":   "Consumer Discretionary",
    "ZAL GY":    "Consumer Discretionary",
    "DHER GY":   "Consumer Discretionary",
    "P911 GY":   "Consumer Discretionary",
    "HMB SS":    "Consumer Discretionary",
    "RATOB SS":  "Consumer Discretionary",
    "THULE SS":  "Consumer Discretionary",
    "EVO SS":    "Consumer Discretionary",
    "VPLAYB SS": "Consumer Discretionary",
    "BILL SS":   "Consumer Discretionary",
    "MIPS SS":   "Consumer Discretionary",
    "ITX SQ":    "Consumer Discretionary",
    "SAB SQ":    "Consumer Discretionary",
    "DIA SQ":    "Consumer Discretionary",
    "DIA IM":    "Consumer Discretionary",
    "EBRO SQ":   "Consumer Discretionary",
    "MKS LN":    "Consumer Discretionary",
    "NXT LN":    "Consumer Discretionary",
    "KGF LN":    "Consumer Discretionary",
    "ITV LN":    "Consumer Discretionary",
    "WPP LN":    "Consumer Discretionary",
    "RKT LN":    "Consumer Discretionary",
    "BRBY LN":   "Consumer Discretionary",
    "OCDO LN":   "Consumer Discretionary",
    "DOM LN":    "Consumer Discretionary",
    "THG LN":    "Consumer Discretionary",
    "FUTR LN":   "Consumer Discretionary",
    "AUTO LN":   "Consumer Discretionary",
    "RMV LN":    "Consumer Discretionary",
    "JD/ LN":    "Consumer Discretionary",
    "RACE IM":   "Consumer Discretionary",
    "PNDORA DC": "Consumer Discretionary",
    "BAVA DC":   "Consumer Discretionary",
    "WTB LN":    "Consumer Discretionary",
    "SMWH LN":   "Consumer Discretionary",
    "ENT LN":    "Consumer Discretionary",
    "WLN FP":    "Consumer Discretionary",
    "AKE FP":    "Consumer Discretionary",
    "UBI FP":    "Consumer Discretionary",
    "BVI FP":    "Consumer Discretionary",
    "VID SQ":    "Consumer Discretionary",
    "TPK LN":    "Consumer Discretionary",
    "GRG LN":    "Consumer Discretionary",
    "GAW LN":    "Consumer Discretionary",
    "CURY LN":   "Consumer Discretionary",
    "CHG LN":    "Consumer Discretionary",
    "GNS LN":    "Consumer Discretionary",
    "STLAM IM":  "Consumer Discretionary",
    "FBK IM":    "Consumer Discretionary",
    "CEC GY":    "Consumer Discretionary",
    "HFG GY":    "Consumer Discretionary",
    "AVOL SE":   "Consumer Discretionary",
    "BB FP":     "Consumer Discretionary",
    "BC IM":     "Consumer Discretionary",
    "BME LN":    "Consumer Discretionary",
    "CFR SE":    "Consumer Discretionary",
    "CON GY":    "Consumer Discretionary",
    "CPG LN":    "Consumer Discretionary",
    "EVD GY":    "Consumer Discretionary",
    "INCH LN":   "Consumer Discretionary",
    "JM SS":     "Consumer Discretionary",
    "MONC IM":   "Consumer Discretionary",
    "RCH LN":    "Consumer Discretionary",
    "RNK LN":    "Consumer Discretionary",
    "SSPG LN":   "Consumer Discretionary",
    "SW FP":     "Consumer Discretionary",
    "TRN LN":    "Consumer Discretionary",
    "TW/ LN":    "Consumer Discretionary",
    "TYRES FH":  "Consumer Discretionary",
    "UHR SE":    "Consumer Discretionary",
    "VOLCARB SS":"Consumer Discretionary",
    "AG1 GY":    "Consumer Discretionary",
    "AVOL SW":   "Consumer Discretionary",
    "BWIN AV":   "Consumer Discretionary",
    "CFR SW":    "Consumer Discretionary",
    "CSP LN":    "Consumer Discretionary",
    "DEB LN":    "Consumer Discretionary",
    "DXNS LN":   "Consumer Discretionary",
    "EIG LN":    "Consumer Discretionary",
    "F IM":      "Consumer Discretionary",
    "FLTR LN":   "Consumer Discretionary",
    "FRAS LN":   "Consumer Discretionary",
    "GNK LN":    "Consumer Discretionary",
    "HMV LN":    "Consumer Discretionary",
    "KINDSDB SS":"Consumer Discretionary",
    "LPP PW":    "Consumer Discretionary",
    "LUX IM":    "Consumer Discretionary",
    "MERL LN":   "Consumer Discretionary",
    "ROO LN":    "Consumer Discretionary",
    "RTN LN":    "Consumer Discretionary",
    "SNH GY":    "Consumer Discretionary",
    "TCG LN":    "Consumer Discretionary",
    "TOD IM":    "Consumer Discretionary",
    "TT/ LN":    "Consumer Discretionary",
    "TUI LN":    "Consumer Discretionary",
    "TUIJ LN":   "Consumer Discretionary",
    "UG FP":     "Consumer Discretionary",
    "UHR SW":    "Consumer Discretionary",
    "WMH LN":    "Consumer Discretionary",
    "DL NA":     "Consumer Discretionary",
    "GAMBA SS":  "Consumer Discretionary",
    "JAZ SQ":    "Consumer Discretionary",
    "PARG SE":   "Consumer Discretionary",
    "TKWY NA":   "Consumer Discretionary",
    "BET LN":    "Consumer Discretionary",
    "BFI IM":    "Consumer Discretionary",
    "BKWN SE":   "Consumer Discretionary",
    "CAN LN":    "Consumer Discretionary",
    "DRTY LN":   "Consumer Discretionary",
    "GFS LN":    "Consumer Discretionary",
    "HNS LN":    "Consumer Discretionary",
    "IAW ID":    "Consumer Discretionary", 
    "KEL LN":    "Consumer Discretionary",
    "MDC LN":    "Consumer Discretionary",
    "NXG LN":    "Consumer Discretionary",
    "SPW LN":    "Consumer Discretionary",
    "TRIL LN":   "Consumer Discretionary",
    "ULE LN":    "Consumer Discretionary",
    "WLB LN":    "Consumer Discretionary",
    "WPG LN":    "Consumer Discretionary",
    "ZEG LN":    "Consumer Discretionary", 

    "ABI BB":    "Consumer Staples",
    "AD NA":     "Consumer Staples",
    "BN FP":     "Consumer Staples",
    "CA FP":     "Consumer Staples",
    "CO FP":     "Consumer Staples",
    "COLR BB":   "Consumer Staples",
    "DG FP":     "Consumer Staples",
    "OR FP":     "Consumer Staples",
    "BEI GY":    "Consumer Staples",
    "HEN3 GY":   "Consumer Staples",
    "HEIA NA":   "Consumer Staples",
    "HEIO NA":   "Consumer Staples",
    "ELUXB SS":  "Consumer Staples",
    "INVEB SS":  "Consumer Staples",
    "HUH1V FH":  "Consumer Staples",
    "KNEBV FH":  "Consumer Staples",
    "KESKOB FH": "Consumer Staples",
    "SANOMA FH": "Consumer Staples",
    "ABF LN":    "Consumer Staples",
    "ULVR LN":   "Consumer Staples",
    "BATS LN":   "Consumer Staples",
    "IMB LN":    "Consumer Staples",
    "TATE LN":   "Consumer Staples",
    "MARS LN":   "Consumer Staples",
    "CARLB DC":  "Consumer Staples",
    "AMBUB DC":  "Consumer Staples",
    "NESN SE":   "Consumer Staples",
    "WHA NA":    "Consumer Staples",
    "ONTEX BB":  "Consumer Staples",
    "JMT PL":    "Consumer Staples",
    "GALE SE":   "Consumer Staples",
    "TSCO LN":   "Consumer Staples",
    "SBRY LN":   "Consumer Staples",
    "BARN SE":   "Consumer Staples",
    "AAK SS":    "Consumer Staples",
    "CCH LN":    "Consumer Staples",
    "CWK LN":    "Consumer Staples",
    "DGE LN":    "Consumer Staples",
    "KSP ID":    "Consumer Staples",
    "LISN SE":   "Consumer Staples",
    "SALM NO":   "Consumer Staples",
    "ARYN SE":   "Consumer Staples",
    "ARYN SW":   "Consumer Staples",
    "BVIC LN":   "Consumer Staples",
    "CBRY LN":   "Consumer Staples",
    "DELB BB":   "Consumer Staples",
    "EEE GA":    "Consumer Staples",
    "ICA SS":    "Consumer Staples",
    "LISN SW":   "Consumer Staples",
    "MRW LN":    "Consumer Staples",
    "NESN SW":   "Consumer Staples",
    "PUIG SQ":   "Consumer Staples",
    "SAB LN":    "Consumer Staples",
    "SWMA SS":   "Consumer Staples",
    "UL NA":     "Consumer Staples",
    "ALIFB SS":  "Consumer Staples",
    "BUD AV":    "Consumer Staples",
    "LOR FP":    "Consumer Staples",
    "NOBN SE":   "Consumer Staples",
    "PGIL LN":   "Consumer Staples",
    "BRI PL":    "Consumer Staples",
    "GN5 ID":    "Consumer Staples",

    "BAYN GY":   "Health Care",
    "MRK GY":    "Health Care",
    "SRT3 GY":   "Health Care",
    "NOVN SE":   "Health Care",
    "ROG SE":    "Health Care",
    "ALC SE":    "Health Care",
    "ALLN SE":   "Health Care",
    "BEAN SE":   "Health Care",
    "SDZ SE":    "Health Care",
    "SFSN SE":   "Health Care",
    "DOCM SE":   "Health Care",
    "SCHP SE":   "Health Care",
    "AZN LN":    "Health Care",
    "GSK LN":    "Health Care",
    "SHP LN":    "Health Care",
    "SN/ LN":    "Health Care",
    "HLN LN":    "Health Care",
    "HIK LN":    "Health Care",
    "HLMA LN":   "Health Care",
    "PHP LN":    "Health Care",
    "SDR LN":    "Health Care",
    "CTEC LN":   "Health Care",
    "GNS LN":    "Health Care",
    "LMP LN":    "Health Care",
    "GRI LN":    "Health Care",
    "DOCS LN":   "Health Care",
    "ONT LN":    "Health Care",
    "NOVOB DC":  "Health Care",
    "GMAB DC":   "Health Care",
    "DEMANT DC": "Health Care",
    "COLOB DC":  "Health Care",
    "ALKB DC":   "Health Care",
    "NETC DC":   "Health Care",
    "SYENS BB":  "Health Care",
    "UCB BB":    "Health Care",
    "ARGX BB":   "Health Care",
    "ORNBV FH":  "Health Care",
    "ELI BB":    "Health Care",
    "SOBI SS":   "Health Care",
    "ESSITYB SS":"Health Care",
    "ADDTB SS":  "Health Care",
    "ABE SQ":    "Health Care",
    "GRF SQ":    "Health Care",
    "AMS SQ":    "Health Care",
    "TRE SQ":    "Health Care",
    "FAE SQ":    "Health Care",
    "CPR IM":    "Health Care",
    "BMED IM":   "Health Care",
    "BGN IM":    "Health Care",
    "PRY IM":    "Health Care",
    "AMP IM":    "Health Care",
    "PIRC IM":   "Health Care",
    "REC IM":    "Health Care",
    "REY IM":    "Health Care",
    "FRES LN":   "Health Care",
    "TEMN SE":   "Health Care",
    "MYCR SS":   "Health Care",
    "BAVA DC":   "Health Care",
    "NSISB DC":  "Health Care",
    "IPN FP":    "Health Care",
    "BIM FP":    "Health Care",
    "DIM FP":    "Health Care",
    "EKTAB SS":  "Health Care",
    "EL FP":     "Health Care",
    "ERF FP":    "Health Care",
    "EVT GY":    "Health Care",
    "FME GY":    "Health Care",
    "FRE GY":    "Health Care",
    "GALD SE":   "Health Care",
    "GIB GY":    "Health Care",
    "GN DC":     "Health Care",
    "GXI GY":    "Health Care",
    "LONN SE":   "Health Care",
    "PHAR LN":   "Health Care",
    "PHIA NA":   "Health Care",
    "QIA GY":    "Health Care",
    "RHK GY":    "Health Care",
    "SHL GY":    "Health Care",
    "SOON SE":   "Health Care",
    "STMN SE":   "Health Care",
    "TECN SE":   "Health Care",
    "ZEAL DC":   "Health Care",
    "ABVX FP":   "Health Care",
    "ALAPIS GA": "Health Care",
    "ATLN SW":   "Health Care",
    "CRXL NA":   "Health Care",
    "DPH LN":    "Health Care",
    "ELN ID":    "Health Care",
    "EMEIS FP":  "Health Care",
    "FRE3 GY":   "Health Care",
    "HLUNB DC":  "Health Care",
    "IDIA SE":   "Health Care",
    "INDV LN":   "Health Care",
    "LONN SW":   "Health Care",
    "MEDAA SS":  "Health Care",
    "MOR GY":    "Health Care",
    "NMC LN":    "Health Care",
    "NOVN SW":   "Health Care",
    "ROG SW":    "Health Care",
    "SOON SW":   "Health Care",
    "UDG LN":    "Health Care",
    "VIFN SE":   "Health Care",
    "VIFN SW":   "Health Care",
    "VITR SS":   "Health Care",
    "ALT FP":    "Health Care",
    "ATCT NA":   "Health Care",
    "CHRN SE":   "Health Care",
    "LUMO FH":   "Health Care",
    "OXUR BB":   "Health Care",
    "PPHN SW":   "Health Care",
    "SCHP SW":   "Health Care", 
    "SYNN SW":   "Health Care",
    "ZOT SQ":    "Health Care",
    "ALPH SE":   "Health Care",
    "BUL IM":    "Health Care",
    "GLH LN":    "Health Care",
    "HVM GY":    "Health Care",
    "TEC FP":    "Health Care",

    "ABDN LN":   "Financials",
    "ACA FP":    "Financials",
    "AGS BB":    "Financials",
    "BNP FP":    "Financials",
    "GLE FP":    "Financials",
    "SAN FP":    "Financials",
    "CS FP":     "Financials",
    "ML FP":     "Financials",
    "AMUN FP":   "Financials",
    "MMB FP":    "Financials",
    "LOCAL FP":  "Financials",
    "ALV GY":    "Financials",
    "MUV2 GY":   "Financials",
    "CBK GY":    "Financials",
    "DBK GY":    "Financials",
    "HNR1 GY":   "Financials",
    "HLE GY":    "Financials",
    "AT1 GY":    "Financials",
    "AFX GY":    "Financials",
    "RDC GY":    "Financials",
    "AGFB BB":   "Financials",
    "KBC BB":    "Financials",
    "GBLB BB":   "Financials",
    "COFB BB":   "Financials",
    "BEKB BB":   "Financials",
    "ACKB BB":   "Financials",
    "NYR BB":    "Financials",
    "AED BB":    "Financials",
    "AGN NA":    "Financials",
    "INGA NA":   "Financials",
    "NN NA":     "Financials",
    "RAND NA":   "Financials",
    "ASRNL NA":  "Financials",
    "ABN NA":    "Financials",
    "PNL NA":    "Financials",
    "BBVA SQ":   "Financials",
    "BKT SQ":    "Financials",
    "CABK SQ":   "Financials",
    "SAB SQ":    "Financials",
    "SAN SQ":    "Financials",
    "BAMI IM":   "Financials",
    "BMPS IM":   "Financials",
    "ISP IM":    "Financials",
    "MB IM":     "Financials",
    "UCG IM":    "Financials",
    "UNI IM":    "Financials",
    "MFEB IM":   "Financials",
    "G IM":      "Financials",
    "PST IM":    "Financials",
    "INW IM":    "Financials",
    "AZM IM":    "Financials",
    "BPE IM":    "Financials",
    "BPSO IM":   "Financials",
    "HSBA LN":   "Financials",
    "LLOY LN":   "Financials",
    "BARC LN":   "Financials",
    "NWG LN":    "Financials",
    "STAN LN":   "Financials",
    "PRU LN":    "Financials",
    "LGEN LN":   "Financials",
    "AV/ LN":    "Financials",
    "INVP LN":   "Financials",
    "JUP LN":    "Financials",
    "ASHM LN":   "Financials",
    "EVR LN":    "Financials",
    "III LN":    "Financials",
    "LRE LN":    "Financials",
    "UTG LN":    "Financials",
    "QLT LN":    "Financials",
    "OMU LN":    "Financials",
    "PFD LN":    "Financials",
    "AIBG ID":   "Financials",
    "BIRG ID":   "Financials",
    "PTSB ID":   "Financials",
    "KYGA ID":   "Financials",
    "DCC ID":    "Financials",
    "GLB ID":    "Financials",
    "RBI AV":    "Financials",
    "EBS AV":    "Financials",
    "VIG AV":    "Financials",
    "TKA AV":    "Financials",
    "VER AV":    "Financials",
    "ANDR AV":   "Financials",
    "ATRS AV":   "Financials",
    "BG AV":     "Financials",
    "VOE AV":    "Financials",
    "WIE AV":    "Financials",
    "SEBA SS":   "Financials",
    "SHBA SS":   "Financials",
    "SWEDA SS":  "Financials",
    "DANSKE DC": "Financials",
    "DNB NO":    "Financials",
    "GJF NO":    "Financials",
    "STB NO":    "Financials",
    "SAMPO FH":  "Financials",
    "UBSG SE":   "Financials",
    "BAER SE":   "Financials",
    "BALN SE":   "Financials",
    "BCVN SE":   "Financials",
    "EFGN SE":   "Financials",
    "PSPN SE":   "Financials",
    "SFZN SE":   "Financials",
    "SLHN SE":   "Financials",
    "SGSN SE":   "Financials",
    "VACN SE":   "Financials",
    "BSLN SE":   "Financials",
    "PGHN SE":   "Financials",
    "BUCN SE":   "Financials",
    "KBCA BB":   "Financials",
    "SOF BB":    "Financials",
    "TRYG DC":   "Financials",
    "RILBA DC":  "Financials",
    "PKO PW":    "Financials",
    "PZU PW":    "Financials",
    "PEO PW":    "Financials",
    "AM FP":     "Financials",
    "BOL FP":    "Financials",
    "TBCG LN":   "Financials",
    "FLTR ID":   "Financials",
    "AZE BB":    "Financials",
    "LOTB BB":   "Financials",
    "LIGHT NA":  "Financials",
    "ALLFG NA":  "Financials",
    "ARCAD NA":  "Financials",
    "DIE BB":    "Financials",
    "INPST NA":  "Financials",
    "BAMNB NA":  "Financials",
    "SBBB SS":   "Financials",
    "BALDB SS":  "Financials",
    "NIBEB SS":  "Financials",
    "BAKKA NO":  "Financials",
    "LUNDB SS":  "Financials",
    "HUFVA SS":  "Financials",
    "WALLB SS":  "Financials",
    "LIFCOB SS": "Financials",
    "LATOB SS":  "Financials",
    "BEZ LN":    "Financials",
    "ADM LN":    "Financials",
    "TCAP LN":   "Financials",
    "FUR NA":    "Financials",
    "SAVE SS":   "Financials",
    "FINGB SS":  "Financials",
    "MF FP":     "Financials",
    "OBEL BB":   "Financials",
    "BESI NA":   "Financials",
    "BCP PL":    "Financials",
    "BION SE":   "Financials",
    "BPI PL":    "Financials",
    "CBG LN":    "Financials",
    "CVC NA":    "Financials",
    "EXO NA":    "Financials",
    "GAM SE":    "Financials",
    "GLJ GY":    "Financials",
    "HSX LN":    "Financials",
    "INDUC SS":  "Financials",
    "JYSK DC":   "Financials",
    "KINVB SS":  "Financials",
    "MAP SQ":    "Financials",
    "PRS NO":    "Financials",
    "SQN SE":    "Financials",
    "STJ LN":    "Financials",
    "VANQ LN":   "Financials",
    "ZURN SE":   "Financials",
    "ADN LN":    "Financials",
    "AGF FP":    "Financials",
    "ALB SQ":    "Financials",
    "ALPHA GA":  "Financials",
    "BAER SW":   "Financials",
    "BALN SW":   "Financials",
    "BGEO LN":   "Financials",
    "BKIA SQ":   "Financials",
    "BME SQ":    "Financials",
    "BNL IM":    "Financials",
    "BPVN IM":   "Financials",
    "CNP FP":    "Financials",
    "CSGN SE":   "Financials",
    "CSGN SW":   "Financials",
    "CVAL IM":   "Financials",
    "DEXB BB":   "Financials",
    "DLG LN":    "Financials",
    "DPB GY":    "Financials",
    "ETE GA":    "Financials",
    "EXISTA IR": "Financials",
    "EXO IM":    "Financials",
    "HBOS LN":   "Financials",
    "HGG LN":    "Financials",
    "HL/ LN":    "Financials",
    "IPF LN":    "Financials",
    "IVZ LN":    "Financials",
    "JLT LN":    "Financials",
    "KAUP IR":   "Financials",
    "KOMB CK":   "Financials",
    "LAIS IR":   "Financials",
    "MBK PW":    "Financials",
    "MIG GA":    "Financials",
    "NDA FH":    "Financials",
    "NDA SS":    "Financials",
    "NRK LN":    "Financials",
    "OML LN":    "Financials",
    "OMX SS":    "Financials",
    "PAS SQ":    "Financials",
    "PGHN SW":   "Financials",
    "PLUS LN":   "Financials",
    "PMI IM":    "Financials",
    "POP SQ":    "Financials",
    "RSA LN":    "Financials",
    "SAGA LN":   "Financials",
    "SCO FP":    "Financials",
    "SLHN SW":   "Financials",
    "SREN SW":   "Financials",
    "TPEIR GA":  "Financials",
    "UBI IM":    "Financials",
    "UBSG SW":   "Financials",
    "UBSN SW":   "Financials",
    "UNIP IM":   "Financials",
    "VMUK LN":   "Financials",
    "ZURN SW":   "Financials",
    "AGS LN":    "Financials",
    "BVA SQ":    "Financials",
    "CAP IM":    "Financials",  
    "CS/ LN":    "Financials",
    "EBP PW":    "Financials",
    "FI IM":     "Financials",
    "NUM NA":    "Financials",
    "UNI SQ":    "Financials",
    "VSURE SS":  "Financials",
    "BI/ LN":    "Financials",
    "BP IM":     "Financials",
    "CPR PL":    "Financials",
    "GBB FP":    "Financials",
    "NDX1 GY":   "Financials",
    "RTRKS FH":  "Financials",
    "SEO VX":    "Financials",
    "SHB LN":    "Financials",
    "VEND NO":   "Financials",
    "TEMP GA":   "Financials",
    "US IM":     "Financials",
    "SDLF LN":   "Financials",
    "ARLN GY":   "Financials",


    "ASML NA":   "Information Technology",
    "SAP GY":    "Information Technology",
    "CAP FP":    "Information Technology",
    "ATO FP":    "Information Technology",
    "DSY FP":    "Information Technology",
    "SESG FP":   "Information Technology",
    "SOI FP":    "Information Technology",
    "SOP FP":    "Information Technology",
    "EDEN FP":   "Information Technology",
    "TOM2 NA":   "Information Technology",
    "ADYEN NA":  "Information Technology",
    "ASM NA":    "Information Technology",
    "DE NA":     "Information Technology",
    "IMCD NA":   "Information Technology",
    "JDEP NA":   "Information Technology",
    "PRX NA":    "Information Technology",
    "SBMO NA":   "Information Technology",
    "WKL NA":    "Information Technology",
    "IFX GY":    "Information Technology",
    "AIXA GY":   "Information Technology",
    "TIETO FH":  "Information Technology",
    "QTCOM FH":  "Information Technology",
    "ERICB SS":  "Information Technology",
    "BEIJB SS":  "Information Technology",
    "SAGAB SS":  "Information Technology",
    "INDT SS":   "Information Technology",
    "HLMA LN":   "Information Technology",
    "LOGN SE":   "Information Technology",
    "TEMN SE":   "Information Technology",
    "SUN SE":    "Information Technology",
    "DKSH SE":   "Information Technology",
    "EMSN SE":   "Information Technology",
    "FHZN SE":   "Information Technology",
    "MOBN SE":   "Information Technology",
    "INRN SE":   "Information Technology",
    "BANB SE":   "Information Technology",
    "STMMI IM":  "Information Technology",
    "NEXI IM":   "Information Technology",
    "G24 GY":    "Information Technology",
    "HFD LN":    "Information Technology",
    "WISE LN":   "Information Technology",
    "CDR PW":    "Information Technology",
    "A3M SQ":    "Information Technology",
    "AMS SE":    "Information Technology",
    "SFOR LN":   "Information Technology",
    "BBOX LN":   "Information Technology",
    "PTEC LN":   "Information Technology",
    "IGG LN":    "Information Technology",
    "ROR LN":    "Information Technology",
    "NOD NO":    "Information Technology",
    "AKAST NO":  "Information Technology",
    "TGS NO":    "Information Technology",
    "RAA GY":    "Information Technology",
    "SY1 GY":    "Information Technology",
    "TLX GY":    "Information Technology",
    "TEG GY":    "Information Technology",
    "MTX GY":    "Information Technology",
    "KBX GY":    "Information Technology",
    "KGX GY":    "Information Technology",
    "MIPS SS":   "Information Technology",
    "SECTB SS":  "Information Technology",
    "STORB SS":  "Information Technology",
    "VIRI FP":   "Information Technology",
    "OPM FP":    "Information Technology",
    "ELIS FP":   "Information Technology",
    "QQ/ LN":    "Information Technology",
    "TMV GY":    "Information Technology",
    "CMBN SE":   "Information Technology",
    "SINCH SS":  "Information Technology",
    "NETC DC":   "Information Technology",
    "NDA GY":    "Information Technology",
    "ATE FP":    "Information Technology",
    "BC8 GY":    "Information Technology",
    "MBTN SE":   "Information Technology",
    "NOKIA FH":  "Information Technology",
    "QDT FP":    "Information Technology",
    "SGE LN":    "Information Technology",
    "ACP PW":    "Information Technology",
    "ALU FP":    "Information Technology",
    "ARM LN":    "Information Technology",
    "AVST LN":   "Information Technology",
    "AVV LN":    "Information Technology",
    "CSR LN":    "Information Technology",
    "DLG GY":    "Information Technology",
    "FNOX SS":   "Information Technology",
    "GTO FP":    "Information Technology",
    "GTO NA":    "Information Technology",
    "LOGN SW":   "Information Technology",
    "MCRO LN":   "Information Technology",
    "NETS DC":   "Information Technology",
    "OCE NA":    "Information Technology",
    "OSR GY":    "Information Technology",
    "PAYS LN":   "Information Technology",
    "SOW GY":    "Information Technology",
    "SPT LN":    "Information Technology",
    "WAF GY":    "Information Technology",
    "WDI GY":    "Information Technology",
    "ADJ GY":    "Information Technology",
    "ATC NA":    "Information Technology",
    "ING FP":    "Information Technology",
    "SIM DC":    "Information Technology",
    "AOX GY":    "Information Technology",
    "B4B GY":    "Information Technology",
    "CLS1 GY":   "Information Technology",
    "DB11 GY":   "Information Technology",
    "DNX LN":    "Information Technology",
    "EEEK GA":   "Information Technology",
    "FTK GY":    "Information Technology",
    "GFJ GY":    "Information Technology",
    "HRX GY":    "Information Technology",
    "IOT LN":    "Information Technology",
    "NETW LN":   "Information Technology",
    "QCE GY":    "Information Technology",
    "R3NK GY":   "Information Technology",
    "SAZ GY":    "Information Technology",
    "SWVK GY":   "Information Technology",
    "SYST VX":   "Information Technology",
    "WIN GY":    "Information Technology",
    "LINU GY":   "Information Technology",   
    "TAA NO":    "Information Technology",
    "TCY LN":    "Information Technology",

    "VIV FP":    "Communication Services",
    "ORA FP":    "Communication Services",
    "VOD LN":    "Communication Services",
    "ITV LN":    "Communication Services",
    "REL LN":    "Communication Services",
    "PSON LN":   "Communication Services",
    "WPP LN":    "Communication Services",
    "EMG LN":    "Communication Services",
    "LSEG LN":   "Communication Services",
    "TEF SQ":    "Communication Services",
    "TIT IM":    "Communication Services",
    "TEL NO":    "Communication Services",
    "TELIA SS":  "Communication Services",
    "TEL2B SS":  "Communication Services",
    "ELISA FH":  "Communication Services",
    "TDC DC":    "Communication Services",
    "KPN NA":    "Communication Services",
    "PROX BB":   "Communication Services",
    "NTGY SQ":   "Communication Services",
    "IDR SQ":    "Communication Services",
    "PRS SQ":    "Communication Services",
    "VIE FP":    "Communication Services",
    "VK FP":     "Communication Services",
    "SK FP":     "Communication Services",
    "ZC FP":     "Communication Services",
    "TOM NO":    "Communication Services",
    "DNORD DC":  "Communication Services",
    "UMG NA":    "Communication Services",
    "LI FP":     "Communication Services",
    "NOS PL":    "Communication Services",
    "GET FP":    "Communication Services",
    "TEP FP":    "Communication Services",
    "CNA LN":    "Communication Services",
    "HMSO LN":   "Communication Services",
    "IHG LN":    "Communication Services",
    "CLNX SQ":   "Communication Services",
    "MRL SQ":    "Communication Services",
    "VIS SQ":    "Communication Services",
    "ANE SQ":    "Communication Services",
    "ENX FP":    "Communication Services",
    "BOL FP":    "Communication Services",
    "PSM GY":    "Communication Services",
    "UTDI GY":   "Communication Services",
    "FNTN GY":   "Communication Services",
    "1U1 GY":    "Communication Services",
    "RRTL GY":   "Communication Services",
    "MNG LN":    "Communication Services",
    "RBREW DC":  "Communication Services",
    "TFI FP":    "Communication Services",
    "RCO FP":    "Communication Services",
    "VRLA FP":   "Communication Services",
    "SUN SE":    "Communication Services",
    "INF LN":    "Communication Services",
    "MTGB SS":   "Communication Services",
    "SCMN SE":   "Communication Services",
    "SUNN SE":   "Communication Services",
    "TUB BB":    "Communication Services",
    "VZN SE":    "Communication Services",
    "HIBU LN":   "Communication Services",
    "AAF LN":    "Communication Services",
    "ADE NO":    "Communication Services",
    "BT/A LN":   "Communication Services",
    "CINE LN":   "Communication Services",
    "COSMO GA":  "Communication Services",
    "CW/ LN":    "Communication Services",
    "CWC LN":    "Communication Services",
    "DMGT LN":   "Communication Services",
    "EMBRACB SS":"Communication Services",
    "EMI LN":    "Communication Services",
    "HAV FP":    "Communication Services",
    "HEM SS":    "Communication Services",
    "HTO GA":    "Communication Services",
    "ILD FP":    "Communication Services",
    "INM ID":    "Communication Services",
    "ISAT LN":   "Communication Services",
    "KD8 GY":    "Communication Services",
    "MICC NA":   "Communication Services",
    "MONY LN":   "Communication Services",
    "NEUF FP":   "Communication Services",
    "O2D GY":    "Communication Services",
    "RTL BB":    "Communication Services",
    "SCMN SW":   "Communication Services",
    "SFR FP":    "Communication Services",
    "SKY LN":    "Communication Services",
    "SKYD GY":   "Communication Services",
    "SPR GY":    "Communication Services",
    "SUN SW":    "Communication Services",
    "TALK LN":   "Communication Services",
    "TIGO SS":   "Communication Services",
    "TL5 SQ":    "Communication Services",
    "TNET BB":   "Communication Services",
    "UBM LN":    "Communication Services",
    "VTWR GY":   "Communication Services",
    "ZIGGO NA":  "Communication Services",
    "CTT LN":    "Communication Services",
    "FORA NA":   "Communication Services",
    "PUB LN":    "Communication Services",
    "VENDA NO":  "Communication Services",
    "ALT SQ":    "Communication Services",
    "BXTN LN":   "Communication Services",
    "EMA LN":    "Communication Services",
    "FLG LN":    "Communication Services",
    "GLB IR":    "Communication Services",
    "IMG LN":    "Communication Services",
    "MSY LN":    "Communication Services",
    "NTV IM":    "Communication Services",
    "OOM LN":    "Communication Services",
    "RGU LN":    "Communication Services",
    "SBT LN":    "Communication Services",
    "SSL LN":    "Communication Services",
    "TNS LN":    "Communication Services",
    "WMPY LN":   "Communication Services",
    "TEM SM":    "Communication Services",

    "A2A IM":    "Utilities",
    "ENEL IM":   "Utilities",
    "EDP PL":    "Utilities",
    "EDPR PL":   "Utilities",
    "ENGI FP":   "Utilities",
    "DTE GY":    "Utilities",
    "EOAN GY":   "Utilities",
    "SRG IM":    "Utilities",
    "TRN IM":    "Utilities",
    "IBE SQ":    "Utilities",
    "ELE SQ":    "Utilities",
    "NG/ LN":    "Utilities",
    "SSE LN":    "Utilities",
    "SVT LN":    "Utilities",
    "UU/ LN":    "Utilities",
    "PNN LN":    "Utilities",
    "SREN SE":   "Utilities",
    "VWS DC":    "Utilities",
    "FORTUM FH": "Utilities",
    "VER AV":    "Utilities",
    "WIE AV":    "Utilities",
    "VNA GY":    "Utilities",
    "SZG GY":    "Utilities",
    "SZU GY":    "Utilities",
    "VATN SE":   "Utilities",
    "ANA SQ":    "Utilities",
    "CNA LN":    "Utilities",
    "VIE FP":    "Utilities",
    "BKW SE":    "Utilities",
    "UN0 GY":    "Utilities",
    "DTE GY":    "Utilities",
    "HER IM":    "Utilities",
    "RED SQ":    "Utilities",
    "AWG LN":    "Utilities",
    "CEZ CK":    "Utilities",
    "ECV GY":    "Utilities",
    "EDF FP":    "Utilities",
    "EGPW IM":   "Utilities",
    "IPR LN":    "Utilities",
    "NEOEN FP":  "Utilities",
    "PPC GA":    "Utilities",
    "SEV FP":    "Utilities",
    "SZE FP":    "Utilities",
    "BES PL":    "Utilities",
    "CEP SQ":    "Utilities",
    "IBR SQ":    "Utilities",    
    "BGY LN":    "Utilities",
    "UNF SQ":    "Utilities",

    "CAST SS":   "Real Estate",
    "WIHL SS":   "Real Estate",
    "HUFVA SS":  "Real Estate",
    "VNA GY":    "Real Estate",
    "LEG GY":    "Real Estate",
    "DWNI GY":   "Real Estate",
    "TGM GY":    "Real Estate",
    "DEQ GY":    "Real Estate",
    "ARO GY":    "Real Estate",
    "WDP BB":    "Real Estate",
    "COFB BB":   "Real Estate",
    "AED BB":    "Real Estate",
    "URW FP":    "Real Estate",
    "GFC FP":    "Real Estate",
    "COV FP":    "Real Estate",
    "SGRO LN":   "Real Estate",
    "LAND LN":   "Real Estate",
    "BLND LN":   "Real Estate",
    "HMSO LN":   "Real Estate",
    "VTY LN":    "Real Estate",
    "BKG LN":    "Real Estate",
    "BWY LN":    "Real Estate",
    "SAFE LN":   "Real Estate",
    "SCT LN":    "Real Estate",
    "LMP LN":    "Real Estate",
    "GRI LN":    "Real Estate",
    "SHC LN":    "Real Estate",
    "ELM LN":    "Real Estate",
    "DLN LN":    "Real Estate",
    "OSB LN":    "Real Estate",
    "WOSG LN":   "Real Estate",
    "CCC LN":    "Real Estate",
    "ENOG LN":   "Real Estate",
    "HBR LN":    "Real Estate",
    "LISP SE":   "Real Estate",
    "PSPN SE":   "Real Estate",
    "SPSN SE":   "Real Estate",
    "IVG IM":    "Real Estate",
    "FUR NA":    "Real Estate",
    "VPK NA":    "Real Estate",
    "SR NA":     "Real Estate",
    "UTG LN":    "Real Estate",
    "DWL LN":    "Real Estate",
    "ORSTED DC": "Real Estate",
    "ENTRA NO":  "Real Estate",
    "BALDB SS":  "Real Estate",
    "WALLB SS":  "Real Estate",
    "NIBEB SS":  "Real Estate",
    "BPTY LN":   "Real Estate",
    "BYG LN":    "Real Estate",
    "COL SQ":    "Real Estate",
    "CORA NA":   "Real Estate",
    "FABG SS":   "Real Estate",
    "GPE LN":    "Real Estate",
    "ICAD FP":   "Real Estate",
    "LCL LN":    "Real Estate",
    "AGR LN":    "Real Estate",
    "INTU LN":   "Real Estate",
    "IVG GY":    "Real Estate",
    "LXI LN":    "Real Estate",
    "SPSN SW":   "Real Estate",
    "UL FP":     "Real Estate",
    "URW NA":    "Real Estate",
    "CXP NA":    "Real Estate",
    "SGC SM":    "Real Estate",  
}


def get_sector(ticker: str) -> str:
    """Return the GICS sector for a Bloomberg ticker, or 'Unknown'."""
    return SECTOR_MAP.get(ticker.strip(), "Unknown")